{{- if and .Values.secrets.enabled .Values.secrets.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.externalSecrets.secrets.name }}
  annotations: {{ toYaml .Values.secrets.externalSecrets.secrets.annotations | nindent 4 }}
  labels:
    helm.sh/chart: {{ include "magento.chart" . }}
    app.kubernetes.io/name: "external-secret"
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- range $key, $val := ($.Values.secrets.externalSecrets.secrets.labels | default dict) }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
spec:
  secretStoreRef:
    name: {{ .Values.secrets.externalSecrets.store.name }}
    kind: SecretStore
  refreshInterval: {{ .Values.secrets.externalSecrets.secrets.refreshInterval | quote }}

  target:
    name: {{ .Values.secrets.name }}
    creationPolicy: {{ .Values.secrets.externalSecrets.secrets.target.creationPolicy }}
    deletionPolicy: {{ .Values.secrets.externalSecrets.secrets.target.deletionPolicy }}
    template:
      metadata:
        {{- if .Values.secrets.externalSecrets.secrets.target.labels }}
        labels:
          {{ toYaml .Values.secrets.externalSecrets.secrets.target.labels | nindent 10 }}
        {{- end }}
        {{- if .Values.secrets.externalSecrets.secrets.target.annotations }}
        annotations:
          {{ toYaml .Values.secrets.externalSecrets.secrets.target.annotations | nindent 10 }}
        {{- end }}
      engineVersion: v2
      data:
        {{ toYaml .Values.secrets.credentials.data | nindent 8 }}
  data:
    {{ toYaml .Values.secrets.externalSecrets.secrets.data | nindent 4 }}

{{- end }}
