{{- if .Values.magento.horizontalPodAutoscaler.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "magento.name" . }}
  labels:
    {{- include "magento.labels" . | nindent 4 }}
    {{- range $key, $val := ($.Values.magento.labels | default dict) }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ include "magento.name" . }}
    apiVersion: apps/v1
  {{- with .Values.magento.horizontalPodAutoscaler }}
  minReplicas: {{ .minCount | default 1 }}
  maxReplicas: {{ .maxCount | default 3 }}
  behavior:
    scaleUp:
      {{- toYaml .scaleUp | nindent 6 }}
    scaleDown:
      {{- toYaml .scaleDown | nindent 6 }}
  metrics:
    {{- toYaml .metrics | nindent 4 }}
  {{- end }}
{{- end }}
