{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "magento.secretName" . }}
  labels:
    helm.sh/chart: {{ include "magento.chart" . }}
    app.kubernetes.io/name: {{ include "magento.secretName" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  {{ if .Values.secrets.externalSecrets.enabled }}

  {{- range $key, $value :=.Values.secrets.externalSecrets.store.credentials }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}

  {{- else }}

  {{- range $key, $value :=.Values.secrets.credentials }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}

  {{- end }}
{{- end }}
