{{- if and .Values.secrets.enabled .Values.secrets.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.secrets.externalSecrets.store.name }}
  labels:
    helm.sh/chart: {{ include "magento.chart" . }}
    app.kubernetes.io/name: "secret-store"
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  {{- if .Values.secrets.externalSecrets.store.controller }}
  controller: {{ .Values.secrets.externalSecrets.store.controller }}
  {{- end }}
  {{- if .Values.secrets.externalSecrets.store.retrySettings }}
  retrySettings:
    {{ toYaml .Values.secrets.externalSecrets.store.retrySettings | nindent 4 }}
  {{- end }}
  provider:
    {{ toYaml .Values.secrets.externalSecrets.store.provider | nindent 4 }}
{{- end }}
