{{- if .Values.serviceHeadless.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "magento.fullname" . }}-headless
  annotations: {{ toYaml .Values.serviceHeadless.annotations | nindent 4 }}
  labels:
    {{- include "magento.labels" . | nindent 4 }}
    {{- range $key, $val := ($.Values.serviceHeadless.labels | default dict) }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  selector: {{- include "magento.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.serviceHeadless.port }}
      targetPort: http
{{- end -}}
