name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.12.1

      - uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.10"

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

#      - name: Run chart-testing (list-changed)
#        id: list-changed
#        run: |
#          changed=$(ct list-changed --charts . --target-branch ${{ github.event.repository.default_branch }})
#          if [[ -n "$changed" ]]; then
#            echo "changed=true" >> "$GITHUB_OUTPUT"
#          fi

      - name: Run chart-testing (lint)
        run: ct lint --charts . --target-branch ${{ github.event.repository.default_branch }} --validate-maintainers=false

      - name: Create kind cluster
#        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.9.0

      - name: Run chart-testing (install)
#        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --charts . --target-branch ${{ github.event.repository.default_branch }}
