name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.12.1

      - uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.10"

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1
        with:
          version: 3.10.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --charts . --target-branch ${{ github.event.repository.default_branch }} --validate-maintainers=false

      - name: Create kind cluster
#        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.9.0
        with:
          version: v0.22.0

      - name: Run chart-testing (install)
#        if: steps.list-changed.outputs.changed == 'true'
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami \
          helm repo add elastic https://helm.elastic.co \
          helm repo add opensearch https://opensearch-project.github.io/helm-charts/ \
          helm repo add softonic https://charts.softonic.io \
          helm repo add imgproxy https://helm.imgproxy.net \
          ct install --charts . --helm-extra-args "--timeout 15m" --target-branch ${{ github.event.repository.default_branch }}
